#!/usr/bin/env node
// Generates Extensions/ShareExtension/Preprocessing.js from the Safari
// extension's extractors.js, so both entry points share one implementation.
//
//   node scripts/build-js.mjs          # write the file
//   node scripts/build-js.mjs --check  # fail if it is out of date (CI)

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const extractors = readFileSync(join(root, "Extensions/SafariExtension/Resources/extractors.js"), "utf8");
const target = join(root, "Extensions/ShareExtension/Preprocessing.js");

const wrapper = `
// Share Extension JavaScript preprocessing. Safari runs this in the page when
// the user taps Share → Listen with Notchman, and passes the result to
// ShareViewModel under NSExtensionJavaScriptPreprocessingResultsKey.
var NotchmanPreprocessor = function () {};
NotchmanPreprocessor.prototype = {
  run: function (args) {
    var payload;
    try {
      payload = NotchmanExtractors.extractPage(document, window.location, {
        selection: String(window.getSelection ? window.getSelection() : ""),
        window: window,
      });
    } catch (error) {
      payload = { url: window.location.href, title: document.title, content: "" };
    }
    args.completionFunction(payload);
  },
  finalize: function () {},
};
var ExtensionPreprocessingJS = new NotchmanPreprocessor();
`;

const output = `// GENERATED by scripts/build-js.mjs from Extensions/SafariExtension/Resources/extractors.js. Do not edit.\n${extractors}${wrapper}`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(target, "utf8"); } catch {}
  if (current !== output) {
    console.error("Preprocessing.js is out of date. Run: node scripts/build-js.mjs");
    process.exit(1);
  }
  console.log("Preprocessing.js is up to date.");
} else {
  writeFileSync(target, output);
  console.log(`Wrote ${target}`);
}
