// GENERATED by scripts/build-js.mjs from Extensions/SafariExtension/Resources/extractors.js. Do not edit.
/*
 * Notchman page extractors.
 *
 * Shared by the Safari Web Extension (content script + popup) and the Share
 * Extension's JavaScript preprocessing (generated into
 * Extensions/ShareExtension/Preprocessing.js by scripts/build-js.mjs).
 *
 * Extractors return only meaningful message text as light markdown, never page
 * chrome: sidebars, navigation, composers, buttons, timestamps and reaction
 * controls are skipped.
 */
(function (root) {
  "use strict";

  // Only offer "Listen" for content at least this long.
  var MIN_LISTEN_LENGTH = 250;

  var SKIP_TAGS = {
    SCRIPT: 1, STYLE: 1, NOSCRIPT: 1, SVG: 1, BUTTON: 1, NAV: 1, FOOTER: 1, HEADER: 1, ASIDE: 1,
    FORM: 1, INPUT: 1, TEXTAREA: 1, SELECT: 1, IFRAME: 1, TEMPLATE: 1, TIME: 1, IMG: 1, VIDEO: 1,
    AUDIO: 1, CANVAS: 1, DIALOG: 1, MENU: 1,
  };
  var BLOCK_TAGS = {
    P: 1, DIV: 1, SECTION: 1, ARTICLE: 1, MAIN: 1, BLOCKQUOTE: 1, UL: 1, OL: 1, TABLE: 1, FIGURE: 1,
    FIGCAPTION: 1, DL: 1, DT: 1, DD: 1, DETAILS: 1, SUMMARY: 1,
  };

  function shouldSkip(el) {
    if (SKIP_TAGS[el.tagName.toUpperCase()]) return true;
    if (el.getAttribute("aria-hidden") === "true") return true;
    if (el.hasAttribute("hidden")) return true;
    if (el.hasAttribute("data-notchman-ignore")) return true;
    if (el.getAttribute("role") === "button" || el.getAttribute("role") === "toolbar") return true;
    var cls = typeof el.className === "string" ? el.className : "";
    if (/(^|\s)(sr-only|visually-hidden|notchman-listen)(\s|$)/.test(cls)) return true;
    return false;
  }

  function codeLanguage(pre) {
    var code = pre.querySelector("code");
    var cls = (code && code.className) || pre.className || "";
    var match = /language-([\w+#-]+)/.exec(cls);
    return match ? match[1] : "";
  }

  /** Converts a DOM subtree into light markdown that Notchman's TextCleaner understands. */
  function elementToMarkdown(node) {
    var out = [];

    function walk(n, listDepth) {
      if (n.nodeType === 3) {
        out.push(n.nodeValue.replace(/\s+/g, " "));
        return;
      }
      if (n.nodeType !== 1) return;
      var el = n;
      if (shouldSkip(el)) return;
      var tag = el.tagName.toUpperCase();

      if (tag === "BR") { out.push("\n"); return; }
      if (tag === "HR") { out.push("\n\n"); return; }

      if (tag === "PRE") {
        var codeEl = el.querySelector("code") || el;
        out.push("\n\n```" + codeLanguage(el) + "\n" + (codeEl.textContent || "").replace(/\n+$/, "") + "\n```\n\n");
        return;
      }
      if (tag === "CODE") {
        out.push("`" + (el.textContent || "") + "`");
        return;
      }
      if (/^H[1-6]$/.test(tag)) {
        out.push("\n\n# ");
        walkChildren(el, listDepth);
        out.push("\n\n");
        return;
      }
      if (tag === "LI") {
        var ordered = el.parentElement && el.parentElement.tagName.toUpperCase() === "OL";
        out.push("\n" + (ordered ? "1. " : "- "));
        walkChildren(el, listDepth + 1);
        out.push("\n");
        return;
      }
      if (tag === "A") {
        var href = el.getAttribute("href") || "";
        var start = out.length;
        walkChildren(el, listDepth);
        var inner = out.splice(start).join("").trim();
        if (/^https?:\/\//.test(href) && inner && inner !== href) {
          out.push("[" + inner + "](" + href + ")");
        } else {
          out.push(inner);
        }
        return;
      }
      if (tag === "TR") {
        var cells = [];
        var children = el.children;
        for (var i = 0; i < children.length; i++) {
          cells.push(normalize(elementToMarkdown(children[i])).replace(/\n+/g, " "));
        }
        out.push("\n| " + cells.join(" | ") + " |\n");
        return;
      }

      var isBlock = BLOCK_TAGS[tag] === 1;
      if (isBlock) out.push("\n\n");
      walkChildren(el, listDepth);
      if (isBlock) out.push("\n\n");
    }

    function walkChildren(el, listDepth) {
      var child = el.firstChild;
      while (child) {
        walk(child, listDepth);
        child = child.nextSibling;
      }
    }

    walk(node, 0);
    return normalize(out.join(""));
  }

  function normalize(text) {
    // Keep code fences intact; tidy whitespace elsewhere.
    var parts = text.split("```");
    for (var i = 0; i < parts.length; i += 2) {
      parts[i] = parts[i]
        .replace(/[ \t]+\n/g, "\n")
        .replace(/\n[ \t]+/g, "\n")
        .replace(/[ \t]{2,}/g, " ");
    }
    return parts.join("```").replace(/\n{3,}/g, "\n\n").trim();
  }

  // ---------------------------------------------------------------------------
  // Site extractors. Each returns [{ element, text }] in page order.

  function outermost(elements) {
    return elements.filter(function (el) {
      return !elements.some(function (other) { return other !== el && other.contains(el); });
    });
  }

  function toArray(list) { return Array.prototype.slice.call(list || []); }

  var ChatGPTExtractor = {
    site: "chatgpt",
    matches: function (host) { return /(^|\.)chatgpt\.com$|(^|\.)chat\.openai\.com$/.test(host); },
    isStreaming: function (el, doc) {
      return !!(el.querySelector(".result-streaming") ||
        (el.closest && el.closest(".result-streaming")) ||
        (el === lastOf(this.messageElements(doc)) && doc.querySelector('[data-testid="stop-button"]')));
    },
    messageElements: function (doc) {
      return toArray(doc.querySelectorAll('[data-message-author-role="assistant"]'));
    },
    blocks: function (doc) {
      return this.messageElements(doc).map(function (el) {
        var body = el.querySelector(".markdown") || el;
        return { element: el, anchor: body, text: elementToMarkdown(body) };
      });
    },
  };

  var ClaudeExtractor = {
    site: "claude",
    matches: function (host) { return /(^|\.)claude\.ai$/.test(host); },
    isStreaming: function (el) {
      var container = el.closest && el.closest("[data-is-streaming]");
      return !!(container && container.getAttribute("data-is-streaming") === "true");
    },
    messageElements: function (doc) {
      var found = toArray(doc.querySelectorAll(
        '.font-claude-response, .font-claude-message, [data-testid="assistant-message"]'));
      return outermost(found).filter(function (el) {
        return !(el.closest && el.closest('[data-testid="user-message"]'));
      });
    },
    blocks: function (doc) {
      return this.messageElements(doc).map(function (el) {
        return { element: el, anchor: el, text: elementToMarkdown(el) };
      });
    },
  };

  var RedditExtractor = {
    site: "reddit",
    matches: function (host) { return /(^|\.)reddit\.com$/.test(host); },
    isStreaming: function () { return false; },
    blocks: function (doc) {
      var blocks = [];

      // New Reddit (shreddit web components).
      toArray(doc.querySelectorAll("shreddit-post")).forEach(function (post) {
        var body = post.querySelector('[slot="text-body"]');
        if (!body) return;
        var titleEl = post.querySelector('[slot="title"]');
        var title = post.getAttribute("post-title") || (titleEl && titleEl.textContent) || "";
        var text = elementToMarkdown(body);
        blocks.push({ element: post, anchor: body, text: title ? "# " + title.trim() + "\n\n" + text : text, title: title.trim() });
      });
      toArray(doc.querySelectorAll("shreddit-comment")).forEach(function (comment) {
        var body = comment.querySelector(':scope > [slot="comment"]');
        if (!body) return;
        var author = comment.getAttribute("author");
        var text = elementToMarkdown(body);
        blocks.push({ element: comment, anchor: body, text: author ? "Comment by " + author + ".\n\n" + text : text });
      });

      // Old Reddit.
      toArray(doc.querySelectorAll(".thing.link .expando .usertext-body .md, .thing.comment > .entry .usertext-body .md"))
        .forEach(function (md) {
          blocks.push({ element: md, anchor: md, text: elementToMarkdown(md) });
        });

      return blocks;
    },
  };

  var SITE_EXTRACTORS = [ChatGPTExtractor, ClaudeExtractor, RedditExtractor];

  function lastOf(list) { return list.length ? list[list.length - 1] : null; }

  function extractorFor(host) {
    host = (host || "").toLowerCase();
    for (var i = 0; i < SITE_EXTRACTORS.length; i++) {
      if (SITE_EXTRACTORS[i].matches(host)) return SITE_EXTRACTORS[i];
    }
    return null;
  }

  /** Message blocks long enough to offer "Listen", excluding ones still streaming. */
  function listenableBlocks(doc, host) {
    var extractor = extractorFor(host);
    if (!extractor) return [];
    return extractor.blocks(doc).filter(function (block) {
      return block.text.length >= MIN_LISTEN_LENGTH && !extractor.isStreaming(block.element, doc);
    }).map(function (block) {
      block.site = extractor.site;
      return block;
    });
  }

  // ---------------------------------------------------------------------------
  // Generic article extraction (readability-lite) for any other page.

  var GenericArticleExtractor = {
    site: "generic",
    extract: function (doc) {
      var candidates = toArray(doc.querySelectorAll("article, main, [role=main], #content, .post, .entry-content"));
      var best = null;
      var bestScore = 0;
      candidates.forEach(function (el) {
        var score = paragraphTextLength(el);
        if (score > bestScore) { best = el; bestScore = score; }
      });
      if (!best || bestScore < 200) {
        // Fall back to the element containing the most paragraph text.
        var counts = new Map();
        toArray(doc.querySelectorAll("p")).forEach(function (p) {
          var parent = p.parentElement;
          if (!parent) return;
          counts.set(parent, (counts.get(parent) || 0) + (p.textContent || "").trim().length);
        });
        counts.forEach(function (value, key) {
          if (value > bestScore) { best = key; bestScore = value; }
        });
      }
      return best ? elementToMarkdown(best) : "";
    },
  };

  function paragraphTextLength(el) {
    return toArray(el.querySelectorAll("p, li, pre, blockquote")).reduce(function (sum, p) {
      return sum + (p.textContent || "").trim().length;
    }, 0);
  }

  /** Index of the block with the most visible area in the viewport; defaults to the last. */
  function focusIndex(blocks, win) {
    if (!blocks.length) return -1;
    var best = blocks.length - 1;
    var bestVisible = 0;
    var height = (win && win.innerHeight) || 0;
    blocks.forEach(function (block, index) {
      if (!block.element.getBoundingClientRect) return;
      var rect = block.element.getBoundingClientRect();
      var visible = Math.max(0, Math.min(rect.bottom, height) - Math.max(rect.top, 0));
      if (visible > bestVisible) { bestVisible = visible; best = index; }
    });
    return best;
  }

  /**
   * Everything Notchman needs from a page, as a plist/JSON-friendly object:
   * { url, title, selection, messages, focusIndex, content, site }
   */
  function extractPage(doc, loc, options) {
    options = options || {};
    var host = (loc && loc.hostname) || "";
    var extractor = extractorFor(host);
    var payload = {
      url: (loc && loc.href) || "",
      title: (doc.title || "").trim(),
      selection: (options.selection || "").trim(),
      site: extractor ? extractor.site : "generic",
    };

    if (extractor) {
      var blocks = extractor.blocks(doc).filter(function (block) { return block.text.length > 0; });
      payload.messages = blocks.map(function (block) { return block.text; });
      payload.focusIndex = focusIndex(blocks, options.window);
      if (extractor.site === "reddit" && blocks.length && blocks[0].title) payload.title = blocks[0].title;
      if (!blocks.length) payload.content = GenericArticleExtractor.extract(doc);
    } else {
      payload.content = GenericArticleExtractor.extract(doc);
    }
    return payload;
  }

  root.NotchmanExtractors = {
    MIN_LISTEN_LENGTH: MIN_LISTEN_LENGTH,
    elementToMarkdown: elementToMarkdown,
    extractorFor: extractorFor,
    listenableBlocks: listenableBlocks,
    extractPage: extractPage,
    GenericArticleExtractor: GenericArticleExtractor,
  };
})(typeof globalThis !== "undefined" ? globalThis : this);

// Share Extension JavaScript preprocessing. Safari runs this in the page when
// the user taps Share → Listen with Notchman, and passes the result to
// ShareViewModel under NSExtensionJavaScriptPreprocessingResultsKey.
var NotchmanPreprocessor = function () {};
NotchmanPreprocessor.prototype = {
  run: function (args) {
    var payload;
    try {
      payload = NotchmanExtractors.extractPage(document, window.location, {
        selection: String(window.getSelection ? window.getSelection() : ""),
        window: window,
      });
    } catch (error) {
      payload = { url: window.location.href, title: document.title, content: "" };
    }
    args.completionFunction(payload);
  },
  finalize: function () {},
};
var ExtensionPreprocessingJS = new NotchmanPreprocessor();
